#!/bin/bash

# set time Russia/Moscow (+3)
sudo timedatectl set-timezone Russia/Moscow

# set locale
sudo dpkg-reconfigure locales

# set 2498 port
sudo sed -i 's/Port 22/Port 2498/g' /etc/ssh/sshd_config

# disable remote login with root
sudo sed -i 's/PermitRootLogin prohibit-password/ PermitRootLogin no/g' /etc/ssh/sshd_config
sudo service ssh restart

# add `usertest` to the system
sudo adduser usertest

# grant sudo rights to `usertest`
sudo usermod -aG sudo usertest

# Alias for added user
sudo sed -i '36i User_Alias TEST_USER = usertest/' /etc/sudoers


# restrict the rights of the created user to start|stop|restart services systemd
sudo sed -i '37i TEST_USER ALL=(ALL) /bin/systemstl start *' 
sudo sed -i '38i TEST_USER ALL=(ALL) /bin/systemstl stop  *' 
sudo sed -i '39i TEST_USER ALL=(ALL) /bin/systemstl restart *' 

# automatic analysis of sudoers
sudo visudo -c

# start nginx
sudo systemctl start nginx
sudo systemctl status nginx

# start monit
sudo systemctl start monit
sudo systemctl status monit

# 
